version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    hostname: nginx-manager
    restart: unless-stopped
    ports:
      - '80:80'    # HTTP
      - '81:81'    # Admin interface
      - '443:443'  # HTTPS
    environment:
      DB_MYSQL_HOST: ${DB_MYSQL_HOST}
      DB_MYSQL_PORT: ${DB_MYSQL_PORT}
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME}
    volumes:
      - /volumes/nginx-manager/app_etc_letsencrypt/_data:/etc/letsencrypt
      - /volumes/nginx-manager/app_data/_data:/data
    networks:
      - default
      - portainer_default
    depends_on:
      - db

  db:
    image: 'yobasystems/alpine-mariadb:latest'
    hostname: nginx-manager-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Altere isso para uma senha segura
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /volumes/nginx-manager/db_data/_data:/var/lib/mysql
    networks:
      - default


networks:
  portainer_default:
    external: true
