services:
  app:
    image: jc21/nginx-proxy-manager:latest
    hostname: nginx-manager
    restart: always
    ports:
      - "80:80"       # Porta para HTTP
      - "443:443"     # Porta para HTTPS
      - "81:81"       # Porta para a interface de gerenciamento
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - /volume/nginx-manager_data/app:/data
    networks:
      - default
      - portainer_default
    #     ipv4_address: 10.0.2.2
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "your_root_password"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - /volume/nginx-manager_data/mysql:/var/lib/mysql
    networks:
      - default



networks:
  portainer_default:
    external: true

# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.0.2.0/24


