services:
  app:
    image: jc21/nginx-proxy-manager:latest
    hostname: nginx-manager
    restart: always
    ports:
      - "80:80"       # Porta para HTTP
      - "443:443"     # Porta para HTTPS
      - "81:81"       # Porta para a interface de gerenciamento
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /docker/nginx-manager/app/letsencrypt:/etc/letsencrypt
      - /data/nginx-manager/app:/data
    networks:
      - default
      - portainer_default
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "your_root_password"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - /data/nginx-manager/db:/var/lib/mysql
    networks:
      - default



networks:
  portainer_default:
    external: true



